### ISSUE TITLE
Support replication

### ISSUE THREAD

**Issue by edumucelli** [canonical/redis-k8s-operator#2]
This operator should support replication. The replication process is described in [this](https://redislabs.com/ebook/part-2-core-concepts/chapter-4-keeping-data-safe-and-ensuring-performance/4-2-replication/) documentation.

**Comment by zmraul** [comment]
Initial implementation on #33

**Comment by zmraul** [comment]
With the addition of Sentinel #34 and #36, replication is complete. Will close when the branch `update` is promoted to main and the charm is published.
