### ISSUE TITLE
Handle non-empty password

### ISSUE THREAD

**Issue by edumucelli** [canonical/redis-k8s-operator#7]
Currently we pass `"ALLOW_EMPTY_PASSWORD": "yes"` in the environment configuration to be read by the underlying `ubuntu/redis` image. However, for scenarios in which a password is required we could:

1. Use one the approaches described in [here](https://discourse.charmhub.io/t/about-sharing-data-between-units/4165) to share the password between units so that all the instances start with the same one.
2. Then the password could be stored in a k8s "resource" as a Opaque secret as in [here](https://github.com/ionutbalutoiu/charm-mssql/blob/11da11810420703287e5135ca020ca85e1871e6c/src/charm.py#L132-L143).

**Comment by zmraul** [comment]
It seems the way to go for db charms is to have a password by default. In that case, #20 solves this issue.

However, the Redis interface with other charms should take this into account. I'll see what changes are needed, testing it with the Discourse bundle in particular.

**Comment by zmraul** [comment]
With #29 this issue should be solved. I won't close it though, since the charm is not yet published (still on the `update` branch), but as soon as we migrate to the new code, I'll close it.
