### ISSUE TITLE
Add Sentinel Master units ip to the app databag

### ISSUE THREAD

**Issue by alithethird** [canonical/redis-k8s-operator#95]
When multiple units of `Redis` is deployed the units put their ip into the unit databag and consumer charms can not find which unit is the leader. An example bug is here: https://github.com/canonical/discourse-k8s-operator/issues/268

This also fixes the issue where after a reboot the consumer charm doesn't refresh the redis ip. Ip refreshes in the unit databag but the charm doesn't read that because its cashed. An example bug is here: https://bugs.launchpad.net/juju/+bug/2063087

Adding the Sentinel Master units ip to the app databag would fix both of these bugs.

**Comment by reneradoi** [comment]
Hello @alithethird thanks for creating this request. Just for clarification: You need the Redis Sentinel leader information, not the `juju` leader, correct?

**Comment by alithethird** [comment]
Hi @reneradoi. Thanks for the answer. Sorry I am not very familiar with and thought they were the same. I need the one that has write access to the database. That is the Sentinel leader I guess?

**Comment by reneradoi** [comment]
Yes @alithethird that would be the Sentinel leader.

**Comment by alithethird** [comment]
Thanks for clarifying that. I will update the issue accordingly.

**Comment by AmberCharitos** [comment]
This is also impacting the Commercial Systems team deployment of Superset. Commenting here for visibility. I see there is a PR to resolve so will monitor that.

**Comment by reneradoi** [comment]
New version has been released as revision 35 to Charmhub.

**Comment by alithethird** [comment]
Thanks a lot!

**Comment by reneradoi** [comment]
Closing the issue as this has been provided with https://github.com/canonical/redis-k8s-operator/pull/96.
